Repository induk-moms/induk-moms-client, pull requests merged in 2024-08, with the labels that each got.

#3 [Setting/#1] 리액트 프로젝트 세팅
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: SETTING

#4 [ci/#2] ci/cd 파이프라인 구축
  .idea/.gitignore
  .idea/aws.xml
  .idea/front.iml
  .idea/modules.xml
  .idea/vcs.xml
  buildspec.yml
Labels: CI

#9 [UI/#5] 동아리 리스트 페이지
  package-lock.json
  package.json
  src/App.js
  src/assets/ic_active_good.svg
  src/assets/ic_active_search.svg
  src/assets/ic_click.svg
  src/assets/ic_good.svg
  src/assets/ic_logo.svg
  src/assets/ic_search.svg
  src/assets/img_top1.svg
  src/assets/img_top2.svg
  src/assets/img_top3.svg
  src/assets/img_top3_background.svg
  src/assets/index.js
  src/index.js
  src/pages/Main/Header.css
  src/pages/Main/Header.js
  src/pages/Main/List.css
  src/pages/Main/List.js
  src/pages/Main/Main.css
  src/pages/Main/Main.js
  src/pages/Main/Top3.css
  src/pages/Main/Top3.js
  src/pages/index.js
Labels: UI

#10 [UI/#7] 동아리 세부 페이지
  package-lock.json
  package.json
  src/App.js
  src/assets/ic_enter.svg
  src/assets/ic_left.svg
  src/assets/index.js
  src/components/Modal.js
  src/components/Modal/ReviewModal.js
  src/components/NavBar.css
  src/components/NavBar.js
  src/components/index.js
  src/pages/Detail/Detail.css
  src/pages/Detail/Detail.js
  src/pages/Detail/Info.js
  src/pages/Detail/Review.js
  src/pages/Main/List.js
  src/pages/Main/Main.css
  src/pages/Main/Main.js
  src/pages/index.js
Labels: UI

#11 [UI/#6] 동아리 검색 페이지
  package-lock.json
  package.json
  src/App.js
  src/assets/ic_black_search.svg
  src/assets/ic_blue_click.svg
  src/assets/ic_x.svg
  src/assets/img_search_background.svg
  src/assets/img_search_result_background.svg
  src/assets/index.js
  src/components/NavBar.js
  src/index.js
  src/pages/Search/Search.css
  src/pages/Search/Search.js
  src/pages/SearchResult/SearchResult.css
  src/pages/SearchResult/SearchResult.js
  src/pages/SearchResult/SliderTemp.js
  src/pages/index.js
Labels: UI

#12 [UI/#8] 퀴즈 및 신청 페이지
  src/App.js
  src/assets/ic_check_blue.svg
  src/assets/ic_check_gray.png
  src/assets/ic_check_gray.svg
  src/assets/ic_question.svg
  src/assets/ic_send.svg
  src/assets/index.js
  src/pages/Detail/Detail.js
  src/pages/Enter/Enter.css
  src/pages/Enter/Enter.js
  src/pages/Quiz/Quiz.css
  src/pages/Quiz/Quiz.js
  src/pages/index.js
Labels: UI

#14 [ADD/#8] 더미 데이터 추가
  src/App.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Info.js
  src/pages/Detail/Review.js
  src/pages/Enter/Enter.js
  src/pages/Main/List.js
  src/pages/Main/Main.js
  src/pages/Main/Top3.css
  src/pages/Main/Top3.js
  src/pages/Quiz/Quiz.js
  src/pages/Search/Search.js
  src/pages/SearchResult/SearchResult.js
Labels: FEAT

#16 feat/#15: 해시태그 추천 동아리 조회 api 연결
  .gitignore
  package-lock.json
  package.json
  src/pages/SearchResult/SearchResult.js
Labels: FEAT
